### ISSUE TITLE
svn unable to connect to repository

### ISSUE THREAD

**Issue by jajajasalu2** [PatchPorting/server-populate#1]
I cloned the repo, ran npm i to install the dependencies and started a mongodb instance on port 27017.
Running npm start fails because svn can't connect to the baseFiles.txt url stated in index.js, which is as follows:

```
const baseFiles = {
  txt: {
    path: './dataFile.txt',
    url: 'svn://scm.alioth.debian.org/svn/secure-testing/data/CVE/list',
    //url: 'https://salsa.debian.org/security-tracker-team/security-tracker/raw/master/data/CVE/list',
  },
  json: {
    path: './dataFile.json',
    url: 'https://security-tracker.debian.org/tracker/data/json',
  },
};
```

commenting the uncommented url above and vice versa gives the same error:

```
jaskaran@jaskaran-H81M-S:~/pps/server-populate$ npm start

> server-populate@0.1.7 start /home/jaskaran/pps/server-populate
> node .


Looking for the default setup in DB ...


(re) downloading the base files ...


Interval set

(node:16014) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
svn: E170013: Unable to connect to a repository at URL 'svn://scm.alioth.debian.org/svn/secure-testing/data/CVE/list'
svn: E670002: Unknown hostname 'scm.alioth.debian.org'

---------- ERROR ----------

{ Error: Command failed: svn export svn://scm.alioth.debian.org/svn/secure-testing/data/CVE/list ./dataFile.txt --non-interactive --force
svn: E170013: Unable to connect to a repository at URL 'svn://scm.alioth.debian.org/svn/secure-testing/data/CVE/list'
svn: E670002: Unknown hostname 'scm.alioth.debian.org'

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'svn export svn://scm.alioth.debian.org/svn/secure-testing/data/CVE/list ./dataFile.txt --non-interactive --force' }
```

Any idea of how to go about this, at least temporarily, or is there something I'm doing wrong here?

**Comment by jajajasalu2** [comment]
Was able to temporarily get around this by using an alternate repo for the list.
